[package]
name = "socks"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = { version = "1", default-features = false }
tokio = { version = "1", features = ["io-util"], default-features = false }